# Streamlit secrets file
# This file is for local development only
# DO NOT commit actual secrets to this file

# Example secrets (users will input their own API keys in the web interface)
# OPENAI_API_KEY = "your-api-key-here"

# For production deployment on Streamlit Cloud:
# Add secrets via the Streamlit Cloud dashboard
# App settings > Secrets > Edit